/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rojion;

import org.json.simple.JSONObject;

import rojion.inference.DJLInference;
import rojion.inference.InferenceFactory;
import rojion.webcam.WebCam;

public class App {
    public static final String VERSION = "0.0.1";
    public static final String APP_NAME = "ROJION";
    public static final String DESCRIPTION = "Real-time Onnx Java Inference ONline";

    public String getGreeting() {
        return APP_NAME + " - " + VERSION + "\n" + DESCRIPTION;
    }

    public static void main(String[] args) throws Exception {
        System.out.println(new App().getGreeting());

        JSONObject params = new JSONObject();
        params.put("threshold", 0.2f);
        // params.put("modelName", "yolov5s.torchscript");

        var factory = new InferenceFactory();
        try {
            var inf = factory.create("YOLO", params);
            // var result = inf.infer("https://github.com/ultralytics/yolov5/raw/master/data/images/bus.jpg");
            // System.out.println(result);
            var webcam = new WebCam();
            webcam.live(((DJLInference)inf).getPredictor());
        } catch (Exception e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        
    }
}
