/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rojion;

import org.json.simple.JSONObject;

import rojion.inference.InferenceFactory;

public class App {
    public static final String VERSION = "0.0.1";
    public static final String APP_NAME = "ROJION";
    public static final String DESCRIPTION = "Real-time Onnx Java Inference ONline";

    public String getGreeting() {
        return APP_NAME + " - " + VERSION + "\n" + DESCRIPTION;
    }

    public static void main(String[] args) throws Exception {
        System.out.println(new App().getGreeting());

        var factory = new InferenceFactory();
        try {
            var inf = factory.create("YOLO", new JSONObject());
            var result = inf.infer();
            System.out.println(result);
        } catch (Exception e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        
    }
}
